### ISSUE TITLE
Downgrade MSRV to 1.80

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#1107]
Seems [1.81 is too new for some distros](https://github.com/dbus2/zbus/pull/1069#issuecomment-2443038761) but [1.80 is fine](https://github.com/dbus2/zbus/pull/1069#issuecomment-2444643319). So let's downgrade to 1.80.

**Comment by ids1024** [comment]
MSRV also seems to be a concern for the `atspi` crate (used by `accesskit`): https://github.com/odilia-app/atspi/pull/209#issuecomment-2458245836.

(It would definitely help if there was some ecosystem agreement about what MSRV is appropriate to target.)

**Comment by luukvanderduim** [comment]
Upstream binaries presumably do not care that much, however, with respect to MSRV, the library ecosystem suffers from what Australians call "tall poppy syndrome". It is generally frowned upon to be the first to adopt a later version than some unspoken agreed upon version. As - over time - incrementing MSRV is inevitable anyway, I cheer for those courageous libraries that blink first and increment MSRV because it is unfortunate we hold each other back like this. 

 We would like `atspi` to be efficient and have a lighter dependency tree whenever we can, thus we welcomed zbus v4 and now v5. The obvious downside is that some users, notably AccessKit, may not be able to use the latest. It is a difficult problem.

**Comment by thomaseizinger** [comment]
Unfortunately, 1.80 is also too high for Tauri (see https://github.com/tauri-apps/plugins-workspace/pull/1953).

I had a brief look and the repository seems to trivially compile (no code changes) on Rust 1.77.2 (that is what Tauri uses due to Windows 7 support). May I ask why a higher MSRV was chosen than what is actually needed for the features used in the code?

**Comment by thomaseizinger** [comment]
I managed to compile `zbus` with `--all-features` on Rust 1.77. May I ask why a higher MSRV was chosen? Rust 1.77 is the last one to support Windows 7 which is why Tauri targets that MSRV.

Currently, Tauri won't update to zbus v5 due to that (see https://github.com/tauri-apps/plugins-workspace/pull/1953#pullrequestreview-2412941091).

Would you consider lowering MSRV to 1.77.2?

**Comment by peterdelevoryas** [comment]
> I managed to compile `zbus` with `--all-features` on Rust 1.77. May I ask why a higher MSRV was chosen than what is actually necessary for the features used? Rust 1.77 is the last one to support Windows 7 which is why Tauri targets that MSRV.
> 
> Currently, Tauri won't update to zbus v5 due to that (see [tauri-apps/plugins-workspace#1953 (review)](https://github.com/tauri-apps/plugins-workspace/pull/1953#pullrequestreview-2412941091)).
> 
> Would you consider lowering MSRV to 1.77.2?

In fact, I'd actually appreciate downgrading to 1.75 (requires only 1-2 changes), the `meta-rust` layer I have access to in Yocto is still on 1.75. `meta-rust-bin` provides the latest stable compiler, but I'm restricted to using `meta-rust` for a lot of practical reasons (can't afford to vendor `meta-rust-bin` in our Yocto project at the moment, would be controversial).

I can compile most of the code with 1.75 pretty easily in https://github.com/dbus2/zbus/commit/86cadfdace76e76749c3f7858528738798c00b27, although I'm actually a little stuck trying to get the tests to compile. This block in zvariant is hard to move back to 1.75:

```
impl_type_with_repr! {
    IpAddr => (u32, &[u8]) {
        ip_addr {
            samples = [IpAddr::V4(Ipv4Addr::LOCALHOST), IpAddr::V6(Ipv6Addr::LOCALHOST)],
            repr(addr) = match addr {
                IpAddr::V4(v4) => (0, &v4.octets()),
                IpAddr::V6(v6) => (1, &v6.octets()),
            },
        }
    }
}
```

:) I'm also fine with using `zbus = "4.4.0"` though, it has no effect on my application, I've been using 4.4.0 so far just fine.

**Comment by thomaseizinger** [comment]
> although I'm actually a little stuck trying to get the tests to compile

Tests don't need to compile on the MSRV because they aren't shipped together with the library on crates.io :)

**Comment by zeenix** [comment]
> I managed to compile `zbus` with `--all-features` on Rust 1.77. May I ask why a higher MSRV was chosen than what is actually necessary for the features used?

I answered this [here](https://github.com/dbus2/zbus/pull/1069#issuecomment-2443489558), that was linked in the description above.

> Currently, Tauri won't update to zbus v5 due to that (see [tauri-apps/plugins-workspace#1953 (review)](https://github.com/tauri-apps/plugins-workspace/pull/1953#pullrequestreview-2412941091)).

I'm sorry to hear that it caused inconvenience.

> Would you consider lowering MSRV to 1.77.2?

It's quite old by now so that would be a bummer but if it helps the Tauri project, I'll accept a PR for this.

**Comment by thomaseizinger** [comment]
> > I managed to compile `zbus` with `--all-features` on Rust 1.77. May I ask why a higher MSRV was chosen than what is actually necessary for the features used?
> 
> I answered this [here](https://github.com/dbus2/zbus/pull/1069#issuecomment-2443489558), that was linked in the description above.

I see, having some leeway in being able to use new features without having to release a new major version makes sense.

> > Would you consider lowering MSRV to 1.77.2?
> 
> It's quite old by now so that would be a bummer but if it helps the Tauri project, I'll accept a PR for this.

I am not affiliated with Tauri so I can't say for sure but I'd assume that if the MSRV is okay, they'd be happy to bump the dependency.

**Comment by peterdelevoryas** [comment]
Disregard my prev comment about 1.75, just upgraded our toolchain to 1.80.1 :) :) :)
