### ISSUE TITLE
Default value for file descriptors

### ISSUE THREAD

**Issue by veljkozy** [dbus2/zbus#1162]
Wanted to write a dbus method which opens a unix socket and passes its file descriptor to the client.
```
    async fn pass_socket(&self) -> zvariant::Fd<'_> {
        
        match tokio::net::UnixStream::connect("/var/run/echo.sock").await {
            Ok(sock) => {
                let sock: std::os::fd::OwnedFd  = sock.into_std().unwrap().into();
                zvariant::Fd::Owned(sock)
            },
            Err(_) => {
                // Return what here?
            }
        }
    }
```

The standard would be to return -1 in case of error, but that is not possible with the current "zvariant::Fd". This is because std lib OwnedFd and BorrowedFd can't be created from -1. 
I see two possibilities:

1. add a RawFd variant to zvariant::Fd, but I'm guessing using RawFd was intentionally avoided due to io safety?
2. add an "invalid" variant that gets serialized to -1 by the library.

**Comment by zeenix** [comment]
Looks like in your case the choice is obvious: you don't have an actual FD to return because of an error so you probably want to make the `pass_socket` fallible and return an error (I think [`zbus::fdo::Error::FileNotFound`](https://docs.rs/zbus/latest/zbus/fdo/enum.Error.html#variant.FileNotFound) is probably what you need here).

If for some reason that option doesn't work for you, there is also the option of wrapping the Fd in an `Option`[ using the `option-as-array` trick](https://dbus2.github.io/zbus/faq.html#2-encoding-as-an-array-a).

Failing that as well, you can have your own custom wrapper type that implements Serialize, Deserialize and Type (with the same signature as that of an FD).

> * add a RawFd variant to zvariant::Fd, but I'm guessing using RawFd was intentionally avoided due to io safety?

We used to do that and we removed it for safety reasons, yes.

> * add an "invalid" variant that gets serialized to -1 by the library.

That would be an API break and not something most folks would need (there is even a good chance nobody will need it) so I'd be reluctant about this option, especially given that thereare solutions and a workarounds possible.

**Comment by veljkozy** [comment]
Will try one of the approaches you proposed, thanks!
