### ISSUE TITLE
Serde Flag (`zvariant`, `zbus_names`)

### ISSUE THREAD

**Issue by TTWNO** [dbus2/zbus#391]
In [`atspi`](https://github.com/odilia-app/atspi/), we wrap `zvariant` and `zbus_names` errors in our `AtspiError` enum. Soon, I'm attempting to write a plugin system based on WASM that will (for now) require (de)serialization on either side of the FFI call.
My current plan is to squash these errors into a `Zvariant(String)`, and `ZbusNames(String)`, errors, but obviously that impacts an upstream user's experience if they want to handle a specific conversion error coming out of atspi.

If I wrote a PR with support for a feature flag that enabled serailziation and deserailization of a few of the types in `zvariant` and `zbus_names`, would that be something you're interested in?

**Comment by zeenix** [comment]
Hi,

Firstly, thanks for the detailed issue and willingness to contribute. 👍

Sounds like something we'd want but you'll need to be a bit more specific, before I can say anything for sure. Almost all zbus_names types already implement the traits in question so I'm curious what you have in mind.

**Comment by TTWNO** [comment]
I'm suggesting that `Serialize` and `Deserialize` be implemented for both `zvariant::Error` and `zbus_names::Error`. I see this could be somewhat problematic for `zvariant` in particular since many of the values contain errors from the standard library which do not implement `De/Serialize`.

Any thoughts on how this could be tackled?

**Comment by zeenix** [comment]
> I'm suggesting that `Serialize` and `Deserialize` be implemented for both `zvariant::Error` and `zbus_names::Error`

I see. Since it's very unusual to implement Serialize/Deserialize traits for error enums, I wonder if you really need this. Did you know that you can use custom error enums on the D-Bus level using the `DBusError` [trait](https://docs.rs/zbus/latest/zbus/trait.DBusError.html)+[derive](https://docs.rs/zbus/latest/zbus/derive.DBusError.html)?

**Comment by zeenix** [comment]
> Any thoughts on how this could be tackled?

We can discuss this more after your response to my previous comment. :) The more I think of this, the more I'm inclined to say "no" since this is a very niche use case, sorry. But even if I say "no", you always have the option of creating wrapper types in your code and implement all the traits you need, on those wrappers.
