### ISSUE TITLE
ProxyProperties documentation and code don't seem to be up to date

### ISSUE THREAD

**Issue by BigfootN** [dbus2/zbus#708]
Hello,

I am interested by the [ProxyProperties](https://docs.rs/zbus/latest/zbus/fdo/struct.PropertiesProxy.html) structure but unfortunately I am unable to figure out how to retrieve/build an instance of this structure.

I am using the `4.1.2` version of this crate and `zbus::fdo::ProxyProperties` doesn't seem exist while `zbus::fdo::Properties` does seem to, and `new` does not seem to be a method part of the `zbus::fdo::Properties` structure.

Also, is there a method like [get_property](https://docs.rs/zbus/latest/zbus/proxy/struct.Proxy.html#method.get_property) but which returns only a `Value` or `OwnedValue`. This way one doesn't have to worry about the `Into<zbus::Error>`.

Thank you very much in advance for any help

**Comment by zeenix** [comment]
> I am interested by the [ProxyProperties](https://docs.rs/zbus/latest/zbus/fdo/struct.PropertiesProxy.html)

Typically that's not something we want to use, since that's the low-level direct D-Bus API wrapper. You likely want to make use of the [`proxy` macro](https://dbus2.github.io/zbus/client.html#properties)'s properties support or the [generic API of underlying Proxy](https://docs.rs/zbus/latest/zbus/proxy/struct.Proxy.html#method.get_property) (as you already noticed).

> I am using the `4.1.2` version of this crate and `zbus::fdo::ProxyProperties` doesn't seem exist while `zbus::fdo::Properties` does seem to, and `new` does not seem to be a method part of the `zbus::fdo::Properties` structure.

I don't think there is anything called `ProxyProperties`. Perhaps you simply misspelled it? The docs are built from the crates.io releases so if they say a type is present in a specific release, it mostly definitely is. :)

As for creating an instance of it, there is a [`new` method](https://docs.rs/zbus/latest/zbus/fdo/struct.PropertiesProxy.html#method.new) that you can use. There is also the [`builder` method](https://docs.rs/zbus/latest/zbus/fdo/struct.PropertiesProxy.html#method.builder) for more control over the proxy creation.

> Also, is there a method like [get_property](https://docs.rs/zbus/latest/zbus/proxy/struct.Proxy.html#method.get_property) but which returns only a `Value` or `OwnedValue`. This way one doesn't have to worry about the `Into<zbus::Error>`

All properties go on the bus as `Value` (`VARIANT` in D-Bus speak) so your type will need to be convertible to/from `Value` in any case. Keep in mind that `From<Infallible> for zbus::Errror` is implemented so the conversion doesn't necessarily have to be fallible.

**Comment by BigfootN** [comment]
Thank you very much for taking your time to explanation and answer.
